theme: jekyll-theme-midnight
title: Geo Systems Developers
url: https://geosytemsdev.com
description: No fluff, just apps that work!
show_downloads: false
google_analytics:
plugins:
- jekyll-seo-tag
- jekyll-sitemap