theme: jekyll-theme-midnight
title: Geo Systems Developers
url: https://geosytemsdev.com
subtitle: No fluff, just apps that work!
description: No fluff, just apps that work!
show_downloads: false
google_analytics: "UA-136522698-1"
plugins:
- jekyll-seo-tag
- jekyll-sitemap