#!/bin/sh

set -e

script/build-inline-css
git diff --exit-code -- _includes/style.css

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri --disable-external
bundle exec rubocop -D
bundle exec script/validate-html
gem build jekyll-theme-midnight.gemspec
